// Code generated by informer-gen. DO NOT EDIT.

package v1

import (
	"context"
	time "time"

	monitoringv1 "github.com/grafana/agent/pkg/operator/apis/monitoring/v1"
	internalinterfaces "github.com/grafana/agent/pkg/operator/client/informers/externalversions/internalinterfaces"
	v1 "github.com/grafana/agent/pkg/operator/client/listers/monitoring/v1"
	versioned "github.com/grafana/agent/pkg/operator/client/versioned"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// GrafanaAgentInformer provides access to a shared informer and lister for
// GrafanaAgents.
type GrafanaAgentInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1.GrafanaAgentLister
}

type grafanaAgentInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewGrafanaAgentInformer constructs a new informer for GrafanaAgent type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewGrafanaAgentInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredGrafanaAgentInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredGrafanaAgentInformer constructs a new informer for GrafanaAgent type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredGrafanaAgentInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options metav1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.MonitoringV1().GrafanaAgents(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options metav1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.MonitoringV1().GrafanaAgents(namespace).Watch(context.TODO(), options)
			},
		},
		&monitoringv1.GrafanaAgent{},
		resyncPeriod,
		indexers,
	)
}

func (f *grafanaAgentInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredGrafanaAgentInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *grafanaAgentInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&monitoringv1.GrafanaAgent{}, f.defaultInformer)
}

func (f *grafanaAgentInformer) Lister() v1.GrafanaAgentLister {
	return v1.NewGrafanaAgentLister(f.Informer().GetIndexer())
}
