// Code generated by informer-gen. DO NOT EDIT.

package v1

import (
	internalinterfaces "github.com/grafana/agent/pkg/operator/client/informers/externalversions/internalinterfaces"
)

// Interface provides access to all the informers in this group version.
type Interface interface {
	// GrafanaAgents returns a GrafanaAgentInformer.
	GrafanaAgents() GrafanaAgentInformer
}

type version struct {
	factory          internalinterfaces.SharedInformerFactory
	namespace        string
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// New returns a new Interface.
func New(f internalinterfaces.SharedInformerFactory, namespace string, tweakListOptions internalinterfaces.TweakListOptionsFunc) Interface {
	return &version{factory: f, namespace: namespace, tweakListOptions: tweakListOptions}
}

// GrafanaAgents returns a GrafanaAgentInformer.
func (v *version) GrafanaAgents() GrafanaAgentInformer {
	return &grafanaAgentInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}
