{{- /*

  .Use:      Set to true for if honorLabels is set, false otherwise
  .Override: Set to true if being overridden, false otherwise

  Equivalent Go code:

    if Use && Override {
      return false
    }
    return Use

*/ -}}

{{- if (and .Use .Override) -}}
false
{{- else -}}
{{ yaml .Use }}
{{- end -}}


