{{- /*
  remote_write.yaml generates the contents of a remote_write block.
  Pipeline value should be a map where:

    .Namespace: Namespace of the parent object
    .Spec:      Remote write spec to render

  TODO(rfratto): follow_redirects
  TODO(rfratto): retry_on_http_429, currently experimental
*/ -}}

url: {{ .Spec.URL }}
{{ yamlField "name" .Spec.Name }}
{{ yamlField "remote_timeout" .Spec.RemoteTimeout }}
{{ yamlField "headers" .Spec.Headers | nindent 2 }}

{{ if .Spec.WriteRelabelConfigs }}
write_relabel_configs:
  {{ range $relabel := .Spec.WriteRelabelConfigs }}
  - {{- include "component/write_relabel_config.yaml" $relabel | nindent 4 }}
  {{ end }}
{{ end }}

{{ if .Spec.TLSConfig }}
tls_config:
  {{ $ctx := dict "Namespace" .Namespace "Spec" .Spec.TLSConfig }}
  {{- include "component/tls_config.yaml" $ctx | nindent 2 }}
{{ end }}

{{ if .Spec.BasicAuth }}
basic_auth:
  username: {{ secretValue .Namespace .Spec.BasicAuth.Username }}
  password: {{ secretValue .Namespace .Spec.BasicAuth.Password }}
{{ end }}

{{ if .Spec.SigV4 }}
sigv4:
  {{ yamlField "region" .Spec.SigV4.Region }}
  {{ yamlField "profile" .Spec.SigV4.Profile }}
  {{ yamlField "role_arn" .Spec.SigV4.RoleARN }}
  {{ yamlField "access_key" (secretValue .Namespace .Spec.SigV4.AccessKey) }}
  {{ yamlField "secret_key" (secretValue .Namespace .Spec.SigV4.SecretKey) }}
{{ end }}

{{ if .Spec.QueueConfig }}
queue_config:
  {{ yamlField "capacity" .Spec.QueueConfig.Capacity }}
  {{ yamlField "max_shards" .Spec.QueueConfig.MaxShards }}
  {{ yamlField "min_shards" .Spec.QueueConfig.MinShards }}
  {{ yamlField "max_samples_per_send" .Spec.QueueConfig.MaxSamplesPerSend }}
  {{ yamlField "batch_send_deadline" .Spec.QueueConfig.BatchSendDeadline }}
  {{ yamlField "min_backoff" .Spec.QueueConfig.MinBackoff }}
  {{ yamlField "max_backoff" .Spec.QueueConfig.MaxBackoff }}
{{ end }}

{{ if .Spec.MetadataConfig }}
metadata_config:
  send: {{ yaml .Spec.MetadataConfig.Send }}
  {{ yamlField "send_interval" .Spec.MetadataConfig.SendInterval }}
{{ end }}
