{{- /*
  safe_tls_config.yaml generates the contents of a tls_config block, only using
  "safe" settings.

  Pipeline value should be a map where:

    .Namespace: Namespace of the parent object
    .Spec:      SafeTLSConfig to render
*/ -}}

{{ yamlField "ca_file" (secretPath .Namespace .Spec.CA) }}
{{ yamlField "cert_file" (secretPath .Namespace .Spec.Cert) }}
{{ yamlField "key_file" (secretPath .Namespace .Spec.KeySecret) }}
{{ yamlField "server_name" .Spec.ServerName }}
{{ yamlField "insecure_skip_verify" .Spec.InsecureSkipVerify }}
