{{- /*
  write_relabel_config.yaml generates the contents of a tls_config block.
  Pipeline value should be a RelabelConfig.
*/ -}}

{{ yamlField "source_labels" .SourceLabels }}
{{ yamlField "separator" .Separator }}
{{ yamlField "regex" .Regex }}
{{ yamlField "modulus" .Modulus }}
{{ yamlField "target_label" .TargetLabel }}
{{ yamlField "replacement" .Replacement }}
{{ yamlField "action" .Action }}
