{{- /*
  prometheus.yaml generates a Prometheus config.
  Pipeline value should be a map where:

    .Agent:                   The owning Agent
    .Spec:                    The PrometheusInstance object.
*/ -}}

{{ $namespace                := .Spec.Instance.Namespace }}
{{ $agentNamespace           := .Agent.Namespace }}
{{ $apiServer                := .Agent.Spec.APIServerConfig }}
{{ $overrideHonorLabels      := .Agent.Spec.Prometheus.OverrideHonorLabels }}
{{ $overrideHonorTimestamps  := .Agent.Spec.Prometheus.OverrideHonorTimestamps }}
{{ $ignoreNamespaceSelectors := .Agent.Spec.Prometheus.IgnoreNamespaceSelectors }}
{{ $enforcedNamespaceLabel   := .Agent.Spec.Prometheus.EnforcedNamepsaceLabel }}
{{ $enforcedSampleLimit      := .Agent.Spec.Prometheus.EnforcedSampleLimit }}
{{ $enforcedTargetLimit      := .Agent.Spec.Prometheus.EnforcedTargetLimit }}
{{ $spec                     := .Spec.Instance.Spec }}

name: {{ $namespace }}/{{ .Spec.Instance.Name }}
{{ yamlField "wal_truncate_frequency" $spec.WALTruncateFrequency }}
{{ yamlField "min_wal_time" $spec.MinWALTime }}
{{ yamlField "max_wal_time" $spec.MaxWALTime }}
{{ yamlField "remote_flush_deadline" $spec.RemoteFlushDeadline }}
{{ yamlField "write_stale_on_shutdown" $spec.WriteStaleOnShutdown }}

{{ if $spec.RemoteWrite }}
remote_write:
  {{ range $rw := $spec.RemoteWrite }}
  {{ $ctx := dict "Namespace" $namespace "Spec" $rw }}
  - {{- include "component/remote_write.yaml" $ctx | nindent 4 }}
  {{ end }}
{{ end }}

{{ if (or .Spec.ServiceMonitors .Spec.PodMonitors .Spec.Probes) }}
scrape_configs:
  {{ range $sMon := .Spec.ServiceMonitors }}
    {{ range $i, $ep := $sMon.Spec.Endpoints }}
      {{
        $ctx := dict
          "AgentNamespace"           $agentNamespace
          "Spec"                     $sMon
          "Endpoint"                 $ep
          "Index"                    $i
          "APIServerConfig"          $apiServer
          "OverrideHonorLabels"      $overrideHonorLabels
          "OverrideHonorTimestamps"  $overrideHonorTimestamps
          "IgnoreNamespaceSelectors" $ignoreNamespaceSelectors
          "EnforcedNamepsaceLabel"   $enforcedNamespaceLabel
          "EnforcedSampleLimit"      $enforcedSampleLimit
          "EnforcedTargetLimit"      $enforcedTargetLimit
      }}
    - {{- include "component/service_monitor.yaml" . | nindent 6 }}
    {{ end }}
  {{ end }}

  {{ range $pMon := .Spec.PodMonitors }}
    {{ range $i, $ep := $pMon.Spec.PodMetricsEndpoints }}
      {{
        $ctx := dict
          "AgentNamespace"           $agentNamespace
          "Spec"                     $pMon
          "Endpoint"                 $ep
          "Index"                    $i
          "APIServerConfig"          $apiServer
          "OverrideHonorLabels"      $overrideHonorLabels
          "OverrideHonorTimestamps"  $overrideHonorTimestamps
          "IgnoreNamespaceSelectors" $ignoreNamespaceSelectors
          "EnforcedNamepsaceLabel"   $enforcedNamespaceLabel
          "EnforcedSampleLimit"      $enforcedSampleLimit
          "EnforcedTargetLimit"      $enforcedTargetLimit
      }}
    - {{- include "component/pod_monitor.yaml" . | nindent 6 }}
    {{ end }}
  {{ end }}

  {{ range $probe := .Spec.Probes }}
    {{
      $ctx := dict
        "AgentNamespace"           $agentNamespace
        "Spec"                     $probe
        "APIServerConfig"          $apiServer
        "OverrideHonorLabels"      $overrideHonorLabels
        "OverrideHonorTimestamps"  $overrideHonorTimestamps
        "IgnoreNamespaceSelectors" $ignoreNamespaceSelectors
        "EnforcedNamepsaceLabel"   $enforcedNamespaceLabel
        "EnforcedSampleLimit"      $enforcedSampleLimit
        "EnforcedTargetLimit"      $enforcedTargetLimit
    }}
    - {{- include "component/pod_monitor.yaml" . | nindent 6 }}
  {{ end }}

  {{ range $scrapeConfig := .Spec.AdditionalScrapeConfigs }}
    - {{ $scrapeConfig | nindent 6 }}
  {{ end }}
{{ end }}
