// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	monitoringv1 "github.com/grafana/agent/pkg/operator/apis/monitoring/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeGrafanaAgents implements GrafanaAgentInterface
type FakeGrafanaAgents struct {
	Fake *FakeMonitoringV1
	ns   string
}

var grafanaagentsResource = schema.GroupVersionResource{Group: "monitoring.grafana.com", Version: "v1", Resource: "grafanaagents"}

var grafanaagentsKind = schema.GroupVersionKind{Group: "monitoring.grafana.com", Version: "v1", Kind: "GrafanaAgent"}

// Get takes name of the grafanaAgent, and returns the corresponding grafanaAgent object, and an error if there is any.
func (c *FakeGrafanaAgents) Get(ctx context.Context, name string, options v1.GetOptions) (result *monitoringv1.GrafanaAgent, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(grafanaagentsResource, c.ns, name), &monitoringv1.GrafanaAgent{})

	if obj == nil {
		return nil, err
	}
	return obj.(*monitoringv1.GrafanaAgent), err
}

// List takes label and field selectors, and returns the list of GrafanaAgents that match those selectors.
func (c *FakeGrafanaAgents) List(ctx context.Context, opts v1.ListOptions) (result *monitoringv1.GrafanaAgentList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(grafanaagentsResource, grafanaagentsKind, c.ns, opts), &monitoringv1.GrafanaAgentList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &monitoringv1.GrafanaAgentList{ListMeta: obj.(*monitoringv1.GrafanaAgentList).ListMeta}
	for _, item := range obj.(*monitoringv1.GrafanaAgentList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested grafanaAgents.
func (c *FakeGrafanaAgents) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(grafanaagentsResource, c.ns, opts))

}

// Create takes the representation of a grafanaAgent and creates it.  Returns the server's representation of the grafanaAgent, and an error, if there is any.
func (c *FakeGrafanaAgents) Create(ctx context.Context, grafanaAgent *monitoringv1.GrafanaAgent, opts v1.CreateOptions) (result *monitoringv1.GrafanaAgent, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(grafanaagentsResource, c.ns, grafanaAgent), &monitoringv1.GrafanaAgent{})

	if obj == nil {
		return nil, err
	}
	return obj.(*monitoringv1.GrafanaAgent), err
}

// Update takes the representation of a grafanaAgent and updates it. Returns the server's representation of the grafanaAgent, and an error, if there is any.
func (c *FakeGrafanaAgents) Update(ctx context.Context, grafanaAgent *monitoringv1.GrafanaAgent, opts v1.UpdateOptions) (result *monitoringv1.GrafanaAgent, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(grafanaagentsResource, c.ns, grafanaAgent), &monitoringv1.GrafanaAgent{})

	if obj == nil {
		return nil, err
	}
	return obj.(*monitoringv1.GrafanaAgent), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeGrafanaAgents) UpdateStatus(ctx context.Context, grafanaAgent *monitoringv1.GrafanaAgent, opts v1.UpdateOptions) (*monitoringv1.GrafanaAgent, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(grafanaagentsResource, "status", c.ns, grafanaAgent), &monitoringv1.GrafanaAgent{})

	if obj == nil {
		return nil, err
	}
	return obj.(*monitoringv1.GrafanaAgent), err
}

// Delete takes name of the grafanaAgent and deletes it. Returns an error if one occurs.
func (c *FakeGrafanaAgents) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(grafanaagentsResource, c.ns, name), &monitoringv1.GrafanaAgent{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeGrafanaAgents) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(grafanaagentsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &monitoringv1.GrafanaAgentList{})
	return err
}

// Patch applies the patch and returns the patched grafanaAgent.
func (c *FakeGrafanaAgents) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *monitoringv1.GrafanaAgent, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(grafanaagentsResource, c.ns, name, pt, data, subresources...), &monitoringv1.GrafanaAgent{})

	if obj == nil {
		return nil, err
	}
	return obj.(*monitoringv1.GrafanaAgent), err
}
