server:
  log_level: debug

metrics:
  global:
    scrape_interval: 15s
  configs:
    - name: default
      scrape_configs:
      - job_name: agent-1
        static_configs:
          - targets: ['127.0.0.1:12345']
      remote_write:
        - url: http://localhost:9009/api/prom/push
