server:
  log_level: debug
  http_listen_port: 12345

prometheus:
  global:
    scrape_interval: 30s
    external_labels:
      cluster: "${AGENT_NAME}"
  configs:
    - name: test
      host_filter: false
      wal_truncate_frequency: 10m
      scrape_configs:
        - job_name: local_scrape
          static_configs:
            - targets: ['127.0.0.1:12345']
              labels:
                container: 'agent'
                pod: '${AGENT_NAME}'
        - job_name: cortex_scrape
          static_configs:
            - targets: ['cortex:9009']
              labels:
                container: 'cortex'

        - job_name: avalanche-1
          static_configs:
            - targets: ['avalanche-1:9001']
              labels:
                container: 'avalanche-1'
        - job_name: avalanche-2
          static_configs:
            - targets: ['avalanche-2:9001']
              labels:
                container: 'avalanche-2'
        - job_name: avalanche-3
          static_configs:
            - targets: ['avalanche-3:9001']
              labels:
                container: 'avalanche-3'
      remote_write:
        - url: http://cortex:9009/api/prom/push

integrations:
  node_exporter:
    enabled: true
  prometheus_remote_write:
    - url: http://cortex:9009/api/prom/push

