// Code generated by lister-gen. DO NOT EDIT.

package v1

// GrafanaAgentListerExpansion allows custom methods to be added to
// GrafanaAgentLister.
type GrafanaAgentListerExpansion interface{}

// GrafanaAgentNamespaceListerExpansion allows custom methods to be added to
// GrafanaAgentNamespaceLister.
type GrafanaAgentNamespaceListerExpansion interface{}
