// Code generated by lister-gen. DO NOT EDIT.

package v1

import (
	v1 "github.com/grafana/agent/pkg/operator/apis/monitoring/v1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// GrafanaAgentLister helps list GrafanaAgents.
type GrafanaAgentLister interface {
	// List lists all GrafanaAgents in the indexer.
	List(selector labels.Selector) (ret []*v1.GrafanaAgent, err error)
	// GrafanaAgents returns an object that can list and get GrafanaAgents.
	GrafanaAgents(namespace string) GrafanaAgentNamespaceLister
	GrafanaAgentListerExpansion
}

// grafanaAgentLister implements the GrafanaAgentLister interface.
type grafanaAgentLister struct {
	indexer cache.Indexer
}

// NewGrafanaAgentLister returns a new GrafanaAgentLister.
func NewGrafanaAgentLister(indexer cache.Indexer) GrafanaAgentLister {
	return &grafanaAgentLister{indexer: indexer}
}

// List lists all GrafanaAgents in the indexer.
func (s *grafanaAgentLister) List(selector labels.Selector) (ret []*v1.GrafanaAgent, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1.GrafanaAgent))
	})
	return ret, err
}

// GrafanaAgents returns an object that can list and get GrafanaAgents.
func (s *grafanaAgentLister) GrafanaAgents(namespace string) GrafanaAgentNamespaceLister {
	return grafanaAgentNamespaceLister{indexer: s.indexer, namespace: namespace}
}

// GrafanaAgentNamespaceLister helps list and get GrafanaAgents.
type GrafanaAgentNamespaceLister interface {
	// List lists all GrafanaAgents in the indexer for a given namespace.
	List(selector labels.Selector) (ret []*v1.GrafanaAgent, err error)
	// Get retrieves the GrafanaAgent from the indexer for a given namespace and name.
	Get(name string) (*v1.GrafanaAgent, error)
	GrafanaAgentNamespaceListerExpansion
}

// grafanaAgentNamespaceLister implements the GrafanaAgentNamespaceLister
// interface.
type grafanaAgentNamespaceLister struct {
	indexer   cache.Indexer
	namespace string
}

// List lists all GrafanaAgents in the indexer for a given namespace.
func (s grafanaAgentNamespaceLister) List(selector labels.Selector) (ret []*v1.GrafanaAgent, err error) {
	err = cache.ListAllByNamespace(s.indexer, s.namespace, selector, func(m interface{}) {
		ret = append(ret, m.(*v1.GrafanaAgent))
	})
	return ret, err
}

// Get retrieves the GrafanaAgent from the indexer for a given namespace and name.
func (s grafanaAgentNamespaceLister) Get(name string) (*v1.GrafanaAgent, error) {
	obj, exists, err := s.indexer.GetByKey(s.namespace + "/" + name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1.Resource("grafanaagent"), name)
	}
	return obj.(*v1.GrafanaAgent), nil
}
